const videoTemplates = [
  [
    "fitness-launch",
    "Fitness Gear Launch",
    "Sports & fitness",
    "Instagram Reels",
    "9:16",
    "15 sec",
    "Product photo, benefits, audience",
    "Product photo|Key benefits|Target audience",
    "Product video, captions, CTA",
    34,
    "Product launch",
    "Sports",
    "Cinematic",
    "Train Stronger",
    "Create an energetic fitness product launch with dynamic close-ups, authentic training motion, benefit captions, rhythmic cuts, and a decisive CTA.",
  ],
  [
    "coffee-story",
    "Artisan Coffee Story",
    "Food & beverage",
    "Instagram Reels",
    "9:16",
    "10 sec",
    "Product photo, origin, tasting notes",
    "Product photo|Origin story|Tasting notes",
    "Brand reel, caption, CTA",
    30,
    "Brand story",
    "Food & beverage",
    "Lifestyle",
    "Taste the Story",
    "Create a warm artisan coffee reel showing beans, brewing ritual, steam, origin details, tasting notes, and an inviting purchase CTA.",
  ],
  [
    "island-travel",
    "Island Escape Teaser",
    "Travel",
    "YouTube",
    "16:9",
    "15 sec",
    "Destination image, highlights, offer",
    "Reference image|Destination highlights|Offer details",
    "Travel teaser, voiceover, captions",
    42,
    "Destination campaign",
    "Travel",
    "Cinematic",
    "Book Your Escape",
    "Create a cinematic island travel teaser with sweeping scenery, local experiences, clear destination highlights, atmospheric sound, and a booking CTA.",
  ],
  [
    "saas-explainer",
    "SaaS Feature Explainer",
    "Technology",
    "LinkedIn",
    "16:9",
    "15 sec",
    "Interface image, feature, benefit",
    "Reference image|Feature details|Customer benefit",
    "Explainer video, headline, caption",
    38,
    "Product explainer",
    "Technology",
    "Minimal",
    "Start Free",
    "Create a polished SaaS feature explainer using clear interface focus, simple animated callouts, a business benefit, captions, and a free-trial CTA.",
  ],
  [
    "pet-care-demo",
    "Happy Pet Product Demo",
    "Pet care",
    "Instagram Reels",
    "9:16",
    "10 sec",
    "Product photo, pet type, benefit",
    "Product photo|Pet type|Key benefit",
    "Demo reel, caption, CTA",
    32,
    "Product demonstration",
    "Pet care",
    "Playful",
    "Treat Your Pet",
    "Create a joyful pet product demonstration with natural pet interaction, product close-ups, benefit captions, playful motion, and a warm CTA.",
  ],
  [
    "electric-car-reveal",
    "Electric Car Reveal",
    "Automotive",
    "YouTube",
    "16:9",
    "15 sec",
    "Vehicle image, model, features",
    "Product photo|Model details|Key features",
    "Reveal film, feature captions, CTA",
    48,
    "Product reveal",
    "Automotive",
    "Cinematic",
    "Book a Test Drive",
    "Create a premium electric vehicle reveal with dramatic light, sculpted details, smooth camera motion, technology callouts, and a test-drive CTA.",
  ],
  [
    "jewelry-sparkle",
    "Fine Jewelry Showcase",
    "Jewelry",
    "Instagram Reels",
    "9:16",
    "10 sec",
    "Product photo, materials, collection",
    "Product photo|Material details|Collection name",
    "Luxury reel, caption, CTA",
    38,
    "Collection showcase",
    "Jewelry",
    "Luxury",
    "Discover the Collection",
    "Create an elegant fine-jewelry showcase with macro sparkle, refined movement, premium materials, graceful pacing, and a collection CTA.",
  ],
  [
    "running-shoe",
    "Running Shoe Performance",
    "Sportswear",
    "Instagram Reels",
    "9:16",
    "15 sec",
    "Shoe image, technology, audience",
    "Product photo|Technology details|Target audience",
    "Performance reel, captions, CTA",
    36,
    "Performance campaign",
    "Sportswear",
    "Cinematic",
    "Run Further",
    "Create a fast-paced running shoe ad showing cushioning, grip, movement, athlete energy, concise technology callouts, and a performance CTA.",
  ],
  [
    "home-decor",
    "Modern Home Decor Tour",
    "Home & living",
    "Pinterest",
    "9:16",
    "15 sec",
    "Room image, products, style",
    "Reference image|Product list|Style details",
    "Decor tour, product captions, CTA",
    35,
    "Room inspiration",
    "Home & living",
    "Lifestyle",
    "Style Your Space",
    "Create a calm modern home decor tour with cohesive styling, natural camera movement, featured-product callouts, and an inspiration-led CTA.",
  ],
  [
    "gadget-unboxing",
    "Tech Gadget Unboxing",
    "Consumer tech",
    "YouTube Shorts",
    "9:16",
    "15 sec",
    "Product photo, features, reaction tone",
    "Product photo|Key features|Reaction tone",
    "Unboxing short, captions, CTA",
    36,
    "Unboxing",
    "Technology",
    "UGC",
    "See What Is Inside",
    "Create an engaging vertical gadget unboxing with a strong hook, satisfying reveal, honest feature reactions, crisp product audio, captions, and CTA.",
  ],
  [
    "eco-brand",
    "Eco Product Mission",
    "Sustainability",
    "LinkedIn",
    "16:9",
    "15 sec",
    "Product image, impact facts, mission",
    "Product photo|Impact facts|Brand mission",
    "Mission video, copy, CTA",
    40,
    "Purpose campaign",
    "Sustainability",
    "Minimal",
    "Choose Better",
    "Create an authentic sustainability brand film with product use, material details, substantiated impact facts, human warmth, and a responsible CTA.",
  ],
  [
    "baby-care",
    "Gentle Baby Care Demo",
    "Baby care",
    "Instagram Reels",
    "9:16",
    "10 sec",
    "Product photo, ingredients, guidance",
    "Product photo|Ingredient details|Usage guidance",
    "Care demo, captions, CTA",
    32,
    "Product demonstration",
    "Baby care",
    "Lifestyle",
    "Care Gently",
    "Create a soft baby-care demonstration with warm daylight, careful product handling, gentle ingredient callouts, safe-use captions, and a reassuring CTA.",
  ],
  [
    "fashion-lookbook",
    "Seasonal Fashion Lookbook",
    "Fashion",
    "Instagram Reels",
    "9:16",
    "15 sec",
    "Collection images, season, style notes",
    "Product photo|Season details|Style notes",
    "Lookbook reel, captions, CTA",
    39,
    "Collection showcase",
    "Fashion",
    "Luxury",
    "Shop the Edit",
    "Create a sophisticated seasonal fashion lookbook with varied styling, fluid model movement, editorial transitions, outfit captions, and a shop CTA.",
  ],
  [
    "game-trailer",
    "Indie Game Trailer",
    "Gaming",
    "YouTube",
    "16:9",
    "15 sec",
    "Game art, genre, features",
    "Reference image|Genre details|Key features",
    "Game trailer, title cards, CTA",
    46,
    "Entertainment launch",
    "Gaming",
    "Cinematic",
    "Wishlist Now",
    "Create an exciting indie game trailer with atmospheric world shots, gameplay-inspired action, escalating pace, bold feature cards, and a wishlist CTA.",
  ],
  [
    "course-promo",
    "Online Course Promo",
    "Education",
    "YouTube",
    "16:9",
    "15 sec",
    "Instructor image, outcomes, audience",
    "Reference image|Learning outcomes|Target audience",
    "Course promo, captions, CTA",
    36,
    "Course launch",
    "Education",
    "Minimal",
    "Enroll Today",
    "Create a credible online-course promo with instructor presence, learning outcomes, lesson glimpses, readable captions, and an enrollment CTA.",
  ],
  [
    "fintech-app",
    "Fintech App Walkthrough",
    "Finance",
    "LinkedIn",
    "16:9",
    "15 sec",
    "App screens, feature, disclaimer",
    "Reference image|Feature details|Compliance disclaimer",
    "App video, caption, CTA",
    40,
    "App promotion",
    "Finance",
    "Minimal",
    "Explore the App",
    "Create a clear fintech app walkthrough with interface-led scenes, secure and compliant language, concise benefit callouts, captions, and CTA.",
  ],
  [
    "wedding-venue",
    "Wedding Venue Film",
    "Events",
    "Instagram Reels",
    "9:16",
    "15 sec",
    "Venue photos, amenities, location",
    "Reference image|Venue amenities|Location",
    "Venue reel, voiceover, CTA",
    42,
    "Venue showcase",
    "Events",
    "Cinematic",
    "Plan Your Day",
    "Create a romantic wedding venue film with elegant spaces, celebration details, natural light, amenity captions, and an inquiry CTA.",
  ],
  [
    "boutique-hotel",
    "Boutique Hotel Tour",
    "Hospitality",
    "Instagram Reels",
    "9:16",
    "15 sec",
    "Hotel photos, amenities, offer",
    "Reference image|Hotel amenities|Offer details",
    "Hotel tour, captions, CTA",
    42,
    "Property showcase",
    "Hospitality",
    "Luxury",
    "Reserve Your Stay",
    "Create an inviting boutique hotel tour featuring arrival, rooms, amenities, dining, local atmosphere, offer captions, and a reservation CTA.",
  ],
  [
    "dental-trust",
    "Dental Clinic Trust Story",
    "Healthcare",
    "Facebook",
    "4:5",
    "15 sec",
    "Clinic image, services, disclaimer",
    "Reference image|Service details|Compliance disclaimer",
    "Trust video, caption, CTA",
    38,
    "Local services",
    "Healthcare",
    "Lifestyle",
    "Book a Consultation",
    "Create a reassuring dental clinic story with welcoming staff, clean environment, patient-centered service highlights, compliant captions, and booking CTA.",
  ],
  [
    "yoga-retreat",
    "Yoga Retreat Invitation",
    "Wellness",
    "Instagram Reels",
    "9:16",
    "15 sec",
    "Retreat image, dates, location",
    "Reference image|Event dates|Location",
    "Retreat reel, voiceover, CTA",
    38,
    "Event promotion",
    "Wellness",
    "Lifestyle",
    "Reserve Your Place",
    "Create a serene yoga retreat invitation with sunrise practice, nature, restorative moments, date and location captions, ambient sound, and CTA.",
  ],
  [
    "meal-kit",
    "Meal Kit in Minutes",
    "Food & beverage",
    "Instagram Reels",
    "9:16",
    "10 sec",
    "Meal image, steps, offer",
    "Product photo|Preparation steps|Offer details",
    "Recipe reel, captions, CTA",
    32,
    "Product demonstration",
    "Food & beverage",
    "Playful",
    "Cook Tonight",
    "Create a lively meal-kit reel showing simple preparation, fresh ingredients, final plating, step captions, offer text, and an order CTA.",
  ],
  [
    "streetwear-drop",
    "Streetwear Drop Teaser",
    "Fashion",
    "TikTok",
    "9:16",
    "10 sec",
    "Collection image, launch date, mood",
    "Product photo|Launch date|Style notes",
    "Drop teaser, captions, CTA",
    35,
    "Limited drop",
    "Fashion",
    "Cinematic",
    "Get the Drop",
    "Create a bold streetwear drop teaser with urban movement, detail cuts, confident styling, launch-date captions, rhythmic sound, and urgency CTA.",
  ],
  [
    "furniture-craft",
    "Handcrafted Furniture Story",
    "Home & living",
    "YouTube",
    "16:9",
    "15 sec",
    "Product image, materials, process",
    "Product photo|Material details|Craft process",
    "Craft film, copy, CTA",
    42,
    "Craft story",
    "Home & living",
    "Luxury",
    "Explore the Craft",
    "Create a tactile furniture craft film with material close-ups, maker process, finished-room reveal, quality captions, and an exploration CTA.",
  ],
  [
    "solar-home",
    "Solar Energy Explainer",
    "Energy",
    "LinkedIn",
    "16:9",
    "15 sec",
    "Installation image, benefits, region",
    "Reference image|Benefit details|Service region",
    "Explainer video, caption, CTA",
    40,
    "Service explainer",
    "Energy",
    "Minimal",
    "Get a Solar Quote",
    "Create an accessible solar-energy explainer with home installation, clean-energy benefits, simple data callouts, regional context, and quote CTA.",
  ],
  [
    "nonprofit-story",
    "Nonprofit Impact Story",
    "Nonprofit",
    "Facebook",
    "4:5",
    "15 sec",
    "Program image, impact data, donation goal",
    "Reference image|Impact facts|Donation goal",
    "Impact film, captions, CTA",
    34,
    "Awareness campaign",
    "Nonprofit",
    "Lifestyle",
    "Support the Mission",
    "Create a respectful nonprofit impact story centered on people, verifiable outcomes, clear context, emotional restraint, and a support CTA.",
  ],
  [
    "book-trailer",
    "Book Launch Trailer",
    "Publishing",
    "Instagram Reels",
    "9:16",
    "15 sec",
    "Cover image, synopsis, launch date",
    "Product photo|Book synopsis|Launch date",
    "Book trailer, captions, CTA",
    34,
    "Entertainment launch",
    "Publishing",
    "Cinematic",
    "Preorder Now",
    "Create an atmospheric book trailer using the cover and story themes, intriguing visual fragments, short review-style hooks, launch date, and preorder CTA.",
  ],
  [
    "gallery-preview",
    "Art Exhibition Preview",
    "Arts & culture",
    "Instagram Reels",
    "9:16",
    "15 sec",
    "Artwork image, artist, dates",
    "Reference image|Artist details|Event dates",
    "Exhibition reel, captions, CTA",
    36,
    "Event promotion",
    "Arts & culture",
    "Minimal",
    "Visit the Exhibition",
    "Create an elegant art exhibition preview with gallery movement, artwork details, artist context, event dates, and a visit CTA.",
  ],
  [
    "conference-teaser",
    "Conference Keynote Teaser",
    "Business",
    "LinkedIn",
    "16:9",
    "15 sec",
    "Speaker image, topic, date",
    "Reference image|Speaker details|Event date",
    "Event teaser, caption, CTA",
    38,
    "Event promotion",
    "Business",
    "Cinematic",
    "Register Now",
    "Create a confident conference keynote teaser with speaker focus, topic hooks, audience energy, event information, captions, and registration CTA.",
  ],
  [
    "app-tutorial",
    "Mobile App Quick Tutorial",
    "Technology",
    "YouTube Shorts",
    "9:16",
    "15 sec",
    "App screens, task, benefit",
    "Reference image|Tutorial steps|User benefit",
    "Tutorial short, captions, CTA",
    36,
    "Tutorial",
    "Technology",
    "Minimal",
    "Try It Now",
    "Create a concise vertical app tutorial with readable interface focus, numbered actions, benefit-led narration, captions, and a try-now CTA.",
  ],
  [
    "recruitment-film",
    "Employer Brand Recruitment Film",
    "Human resources",
    "LinkedIn",
    "16:9",
    "15 sec",
    "Team image, roles, culture points",
    "Reference image|Open roles|Culture details",
    "Recruitment film, caption, CTA",
    40,
    "Recruitment campaign",
    "Business",
    "Lifestyle",
    "Join the Team",
    "Create a human employer-brand film with authentic team moments, workplace culture, open-role highlights, inclusive captions, and an application CTA.",
  ],
];



const fullMotionPreviewById = {
  "book-trailer": "/template-previews/book-trailer-full.mp4",
  "gallery-preview": "/template-previews/gallery-preview-full.mp4",
};

const makeTemplate = (row) => {
  const [
    id,
    name,
    industry,
    platform,
    format,
    duration,
    inputs,
    requirements,
    outputs,
    cost,
    campaignType,
    category,
    style,
    cta,
    prompt,
  ] = row;
  const fullMotionPreview = fullMotionPreviewById[id];
  return {
    id,
    name,
    description: prompt.replace(/^Create /, "A workflow to create "),
    industry,
    platform,
    format,
    duration,
    inputs,
    requirements: requirements.split("|"),
    outputs,
    cost,
    type: "Video + Copy",
    outputType: "Video + Copy",
    campaignType,
    category,
    style,
    cta,
    prompt,
    tone: "blue",
    video: true,
    previewUrl: fullMotionPreview || `/template-previews/${id}.mp4`,
    previewKind: fullMotionPreview ? "full-motion" : "thumbnail-motion",
  };
};

export const additionalTemplates = [
  ...videoTemplates.map((row) => makeTemplate(row)),
];

const expandedTemplateSubjects = [
  ["artisan-perfume-film", "Artisan Perfume Film", "Beauty", "video", "perfume,bottle,luxury", "Luxury"],
  ["streetwear-drop", "Streetwear Drop Reveal", "Fashion", "video", "streetwear,fashion,urban", "Cinematic"],
  ["smartwatch-training", "Smartwatch Training Ad", "Technology", "video", "smartwatch,fitness,runner", "Cinematic"],
  ["organic-tea-ritual", "Organic Tea Ritual", "Food & beverage", "video", "tea,ceremony,organic", "Lifestyle"],
  ["modern-furniture-tour", "Modern Furniture Tour", "Home & living", "video", "furniture,interior,modern", "Minimal"],
  ["mountain-bike-action", "Mountain Bike Action", "Sports", "video", "mountain,bike,action", "Cinematic"],
  ["bakery-morning-reel", "Bakery Morning Reel", "Restaurants", "video", "bakery,bread,pastry", "Lifestyle"],
  ["solar-home-story", "Solar Home Story", "Sustainability", "video", "solar,home,sustainable", "Minimal"],
  ["wedding-venue-film", "Wedding Venue Film", "Events", "video", "wedding,venue,flowers", "Luxury"],
  ["kids-learning-app", "Kids Learning App Demo", "Education", "video", "children,learning,tablet", "Playful"],
  ["skincare-routine-reel", "Skincare Routine Reel", "Beauty", "video", "skincare,serum,routine", "UGC"],
  ["craft-chocolate-story", "Craft Chocolate Story", "Food & beverage", "video", "chocolate,cocoa,artisan", "Luxury"],
  ["coastal-hotel-tour", "Coastal Hotel Tour", "Travel", "video", "hotel,coast,travel", "Cinematic"],
  ["gaming-headset-reveal", "Gaming Headset Reveal", "Gaming", "video", "headset,gaming,neon", "Cinematic"],
  ["financial-app-demo", "Financial App Demo", "Finance", "video", "finance,mobile,app", "Minimal"],
  ["plant-care-guide", "Plant Care Guide", "Home & living", "video", "plants,home,gardening", "Lifestyle"],
  ["handmade-ceramics", "Handmade Ceramics Story", "Ecommerce", "video", "ceramics,pottery,handmade", "Lifestyle"],
  ["electric-scooter-city", "Electric Scooter City Ad", "Automotive", "video", "electric,scooter,city", "Cinematic"],
  ["yoga-retreat-invite", "Yoga Retreat Invitation", "Wellness", "video", "yoga,retreat,nature", "Lifestyle"],
  ["pet-adoption-story", "Pet Adoption Story", "Pet care", "video", "pet,dog,adoption", "Lifestyle"],
  ["architect-portfolio", "Architect Portfolio Film", "Real estate", "video", "architecture,building,modern", "Minimal"],
  ["festival-fashion-reel", "Festival Fashion Reel", "Fashion", "video", "festival,fashion,colorful", "Playful"],
  ["meal-kit-demo", "Meal Kit Demo", "Food & beverage", "video", "meal,cooking,kit", "UGC"],
  ["camera-launch-film", "Camera Launch Film", "Technology", "video", "camera,photography,product", "Cinematic"],
  ["charity-impact-story", "Charity Impact Story", "Nonprofit", "video", "community,charity,people", "Lifestyle"],
  ["eco-packaging-unbox", "Eco Packaging Unboxing", "Ecommerce", "video", "packaging,product,sustainable", "Lifestyle"],
  ["skincare-lab-tour", "Skincare Lab Tour", "Beauty", "video", "skincare,laboratory,serum", "Luxury"],
  ["athlete-day-reel", "Athlete Day in the Life", "Sports", "video", "athlete,training,lifestyle", "Cinematic"],
  ["tech-event-recap", "Tech Event Recap", "Technology", "video", "technology,event,stage", "Cinematic"],
  ["chef-special-reveal", "Chef Special Reveal", "Restaurants", "video", "chef,restaurant,dish", "Lifestyle"],
  ["travel-itinerary-reel", "Travel Itinerary Reel", "Travel", "video", "travel,city,itinerary", "Playful"],
  ["home-workout-demo", "Home Workout Demo", "Sports", "video", "fitness,workout,home", "Cinematic"],
  ["storybook-animation", "Storybook Animation", "Education", "video", "children,storybook,animation", "Playful"],
  ["luxury-property-reel", "Luxury Property Reel", "Real estate", "video", "house,interior,luxury", "Luxury"],
  ["cosmetics-transformation", "Cosmetics Transformation", "Beauty", "video", "beauty,cosmetics,transformation", "UGC"],
  ["film-trailer-teaser", "Film Trailer Teaser", "Entertainment", "video", "cinema,film,trailer", "Cinematic"],
  ["retail-window-showcase", "Retail Window Showcase", "Retail", "video", "retail,shop,display", "Lifestyle"],
  ["language-app-demo", "Language App Demo", "Education", "video", "language,learning,mobile", "Minimal"],
  ["product-feature-spotlight", "Product Feature Spotlight", "Ecommerce", "video", "product,studio,feature", "Minimal"],
  ["newsroom-behind-scenes", "Newsroom Behind the Scenes", "Media", "video", "news,studio,camera", "Cinematic"],
  ["spa-treatment-tour", "Spa Treatment Tour", "Wellness", "video", "spa,wellness,treatment", "Lifestyle"],
  ["museum-exhibit-reel", "Museum Exhibit Reel", "Culture", "video", "museum,art,exhibit", "Minimal"],
  ["car-showroom-walkthrough", "Car Showroom Walkthrough", "Automotive", "video", "car,showroom,luxury", "Luxury"],
  ["event-stage-reveal", "Event Stage Reveal", "Events", "video", "event,stage,lights", "Cinematic"],
  ["food-delivery-demo", "Food Delivery App Demo", "Food & beverage", "video", "food,delivery,mobile", "Playful"],
  ["wildlife-mini-documentary", "Wildlife Mini Documentary", "Media", "video", "nature,wildlife,documentary", "Cinematic"],
  ["saas-dashboard-tour", "SaaS Dashboard Tour", "Technology", "video", "saas,dashboard,business", "Minimal"],
  ["runway-highlight-reel", "Runway Highlight Reel", "Fashion", "video", "fashion,runway,model", "Luxury"],
  ["holiday-gift-guide", "Holiday Gift Guide", "Retail", "video", "holiday,gifts,shopping", "Playful"],
  ["breathwork-visual-guide", "Breathwork Visual Guide", "Wellness", "video", "breathing,wellness,nature", "Lifestyle"],
];

export const expandedTemplates = expandedTemplateSubjects.map(
  ([id, name, industry, , imageKeywords, style], index) => {
    const platform = index % 3 ? "Instagram Reels" : "YouTube";
    const format = platform === "YouTube" ? "16:9" : "9:16";
    const duration = index % 2 ? "15 sec" : "10 sec";
    return {
      id,
      name,
      description: `A ready-made video workflow for ${name.toLowerCase()} with polished pacing and campaign-ready output.`,
      industry,
      platform,
      format,
      duration,
      inputs: "Product or reference image, audience, key message",
      requirements: ["Reference image", "Target audience", "Key message"],
      outputs: "Video ad, captions, CTA",
      cost: 30 + (index % 14),
      type: "Video + Copy",
      outputType: "Video + Copy",
      campaignType: "Video campaign",
      category: industry,
      style,
      cta: "Learn More",
      prompt: `Create a polished ${duration} ${name.toLowerCase()} for ${platform}. Use a ${style.toLowerCase()} direction, a clear opening hook, memorable pacing, and a strong final call to action.`,
      tone: index % 2 ? "amber" : "blue",
      thumbnailUrl: `https://loremflickr.com/640/360/${imageKeywords}?lock=${200 + index}`,
      video: true,
      previewUrl: `/template-previews/${id}.mp4`,
    };
  },
);
